version: '3.7'
services:
  youtube-search:
    container_name: monorepo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
      - 6006:6006
    environment:
      - CHOKIDAR_USEPOLLING=true